apiVersion: v2
name: ucloud-im
type: application
version: 2.0.0

description: "UCloud is an interactive digital research environment"
appVersion: "2026.2.73"
home: "https://github.com/SDU-eScience/UCloud"
