apiVersion: v2
name: ucloud-im
type: application
version: 2.0.3

description: "UCloud is an interactive digital research environment"
appVersion: "2026.4.5"
home: "https://github.com/SDU-eScience/UCloud"
