{{- $namespace := include "ucloud.namespace.inference" . }}
{{- if and .Values.inference.enabled .Values.inference.create_namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end }}
