{{- if .Values.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.server.configSecret" . }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    {{- .Values.server.config | nindent 4 }}
{{- end }}
