apiVersion: v2
name: ucloud-core
type: application
version: 1.0.7

description: "UCloud is an interactive digital research environment"
appVersion: "2026.5.31"
home: "https://github.com/SDU-eScience/UCloud"
