apiVersion: v2
name: ucloud-core
type: application
version: 1.0.3

description: "UCloud is an interactive digital research environment"
appVersion: "2026.2.15"
home: "https://github.com/SDU-eScience/UCloud"
